select 
  penilaian_medis_igd.tanggal,
  penilaian_medis_igd.anamnesis as "anamnesis!",
  penilaian_medis_igd.hubungan as "hubungan!",
  penilaian_medis_igd.keluhan_utama as "keluhan_utama!",
  penilaian_medis_igd.rps as "rps!",
  penilaian_medis_igd.rpk as "rpk!",
  penilaian_medis_igd.rpd as "rpd!",
  penilaian_medis_igd.rpo as "rpo!",
  penilaian_medis_igd.alergi as "alergi!",
  penilaian_medis_igd.keadaan as "keadaan!",
  penilaian_medis_igd.gcs as "gcs!",
  penilaian_medis_igd.kesadaran as "kesadaran!",
  penilaian_medis_igd.td as "td!",
  penilaian_medis_igd.nadi as "nadi!",
  penilaian_medis_igd.rr as "rr!",
  penilaian_medis_igd.suhu as "suhu!",
  penilaian_medis_igd.spo as "spo!",
  penilaian_medis_igd.bb as "bb!",
  penilaian_medis_igd.tb as "tb!",
  penilaian_medis_igd.kepala as "kepala!",
  penilaian_medis_igd.mata as "mata!",
  penilaian_medis_igd.gigi as "gigi!",
  penilaian_medis_igd.leher as "leher!",
  penilaian_medis_igd.thoraks as "thoraks!",
  penilaian_medis_igd.abdomen as "abdomen!",
  penilaian_medis_igd.ekstremitas as "ekstremitas!",
  penilaian_medis_igd.genital as "genital!",
  penilaian_medis_igd.ket_fisik as "ket_fisik!",
  penilaian_medis_igd.ket_lokalis as "ket_lokalis!",
  penilaian_medis_igd.ekg as "ekg!",
  penilaian_medis_igd.rad as "rad!",
  penilaian_medis_igd.lab as "lab!",
  penilaian_medis_igd.diagnosis as "diagnosis!",
  penilaian_medis_igd.tata as "tata!",
  penilaian_medis_igd.kd_dokter as "kode_dokter!",
  dokter.nm_dokter as "nama_dokter!"
from penilaian_medis_igd 
inner join dokter on penilaian_medis_igd.kd_dokter=dokter.kd_dokter 
where penilaian_medis_igd.no_rawat=?
