select
  penilaian_awal_keperawatan_kebidanan.tanggal,
  penilaian_awal_keperawatan_kebidanan.informasi,
  penilaian_awal_keperawatan_kebidanan.td,
  penilaian_awal_keperawatan_kebidanan.nadi,
  penilaian_awal_keperawatan_kebidanan.rr,
  penilaian_awal_keperawatan_kebidanan.suhu,
  penilaian_awal_keperawatan_kebidanan.bb,
  penilaian_awal_keperawatan_kebidanan.gcs,
  penilaian_awal_keperawatan_kebidanan.tb,
  penilaian_awal_keperawatan_kebidanan.bmi,
  penilaian_awal_keperawatan_kebidanan.lila,
  penilaian_awal_keperawatan_kebidanan.tfu,
  penilaian_awal_keperawatan_kebidanan.tbj,
  penilaian_awal_keperawatan_kebidanan.letak,
  penilaian_awal_keperawatan_kebidanan.presentasi,
  penilaian_awal_keperawatan_kebidanan.penurunan,
  penilaian_awal_keperawatan_kebidanan.his,
  penilaian_awal_keperawatan_kebidanan.kekuatan,
  penilaian_awal_keperawatan_kebidanan.lamanya,
  penilaian_awal_keperawatan_kebidanan.bjj,
  penilaian_awal_keperawatan_kebidanan.ket_bjj,
  penilaian_awal_keperawatan_kebidanan.portio,
  penilaian_awal_keperawatan_kebidanan.serviks,
  penilaian_awal_keperawatan_kebidanan.ketuban,
  penilaian_awal_keperawatan_kebidanan.hodge,
  penilaian_awal_keperawatan_kebidanan.inspekulo,
  penilaian_awal_keperawatan_kebidanan.ket_inspekulo,
  penilaian_awal_keperawatan_kebidanan.ctg,
  penilaian_awal_keperawatan_kebidanan.ket_ctg,
  penilaian_awal_keperawatan_kebidanan.usg,
  penilaian_awal_keperawatan_kebidanan.ket_usg,
  penilaian_awal_keperawatan_kebidanan.lab,
  penilaian_awal_keperawatan_kebidanan.ket_lab,
  penilaian_awal_keperawatan_kebidanan.lakmus,
  penilaian_awal_keperawatan_kebidanan.ket_lakmus,
  penilaian_awal_keperawatan_kebidanan.panggul,
  penilaian_awal_keperawatan_kebidanan.keluhan_utama,
  penilaian_awal_keperawatan_kebidanan.umur,
  penilaian_awal_keperawatan_kebidanan.lama,
  penilaian_awal_keperawatan_kebidanan.banyaknya,
  penilaian_awal_keperawatan_kebidanan.haid,
  penilaian_awal_keperawatan_kebidanan.siklus,
  penilaian_awal_keperawatan_kebidanan.ket_siklus,
  penilaian_awal_keperawatan_kebidanan.ket_siklus1,
  penilaian_awal_keperawatan_kebidanan.status,
  penilaian_awal_keperawatan_kebidanan.kali,
  penilaian_awal_keperawatan_kebidanan.usia1,
  penilaian_awal_keperawatan_kebidanan.ket1,
  penilaian_awal_keperawatan_kebidanan.usia2,
  penilaian_awal_keperawatan_kebidanan.ket2,
  penilaian_awal_keperawatan_kebidanan.usia3,
  penilaian_awal_keperawatan_kebidanan.ket3,
  penilaian_awal_keperawatan_kebidanan.hpht,
  penilaian_awal_keperawatan_kebidanan.usia_kehamilan,
  penilaian_awal_keperawatan_kebidanan.tp,
  penilaian_awal_keperawatan_kebidanan.imunisasi,
  penilaian_awal_keperawatan_kebidanan.ket_imunisasi,
  penilaian_awal_keperawatan_kebidanan.g,
  penilaian_awal_keperawatan_kebidanan.p,
  penilaian_awal_keperawatan_kebidanan.a,
  penilaian_awal_keperawatan_kebidanan.hidup,
  penilaian_awal_keperawatan_kebidanan.ginekologi,
  penilaian_awal_keperawatan_kebidanan.kebiasaan,
  penilaian_awal_keperawatan_kebidanan.ket_kebiasaan,
  penilaian_awal_keperawatan_kebidanan.kebiasaan1,
  penilaian_awal_keperawatan_kebidanan.ket_kebiasaan1,
  penilaian_awal_keperawatan_kebidanan.kebiasaan2,
  penilaian_awal_keperawatan_kebidanan.ket_kebiasaan2,
  penilaian_awal_keperawatan_kebidanan.kebiasaan3,
  penilaian_awal_keperawatan_kebidanan.kb,
  penilaian_awal_keperawatan_kebidanan.ket_kb,
  penilaian_awal_keperawatan_kebidanan.komplikasi,
  penilaian_awal_keperawatan_kebidanan.ket_komplikasi,
  penilaian_awal_keperawatan_kebidanan.berhenti,
  penilaian_awal_keperawatan_kebidanan.alasan,
  penilaian_awal_keperawatan_kebidanan.alat_bantu,
  penilaian_awal_keperawatan_kebidanan.ket_bantu,
  penilaian_awal_keperawatan_kebidanan.prothesa,
  penilaian_awal_keperawatan_kebidanan.ket_pro,
  penilaian_awal_keperawatan_kebidanan.adl,
  penilaian_awal_keperawatan_kebidanan.status_psiko,
  penilaian_awal_keperawatan_kebidanan.ket_psiko,
  penilaian_awal_keperawatan_kebidanan.hub_keluarga,
  penilaian_awal_keperawatan_kebidanan.tinggal_dengan,
  penilaian_awal_keperawatan_kebidanan.ket_tinggal,
  penilaian_awal_keperawatan_kebidanan.ekonomi,
  penilaian_awal_keperawatan_kebidanan.budaya,
  penilaian_awal_keperawatan_kebidanan.ket_budaya,
  penilaian_awal_keperawatan_kebidanan.edukasi,
  penilaian_awal_keperawatan_kebidanan.ket_edukasi,
  penilaian_awal_keperawatan_kebidanan.berjalan_a,
  penilaian_awal_keperawatan_kebidanan.berjalan_b,
  penilaian_awal_keperawatan_kebidanan.berjalan_c,
  penilaian_awal_keperawatan_kebidanan.hasil,
  penilaian_awal_keperawatan_kebidanan.lapor,
  penilaian_awal_keperawatan_kebidanan.ket_lapor,
  penilaian_awal_keperawatan_kebidanan.sg1,
  penilaian_awal_keperawatan_kebidanan.nilai1,
  penilaian_awal_keperawatan_kebidanan.sg2,
  penilaian_awal_keperawatan_kebidanan.nilai2,
  penilaian_awal_keperawatan_kebidanan.total_hasil,
  penilaian_awal_keperawatan_kebidanan.nyeri,
  penilaian_awal_keperawatan_kebidanan.provokes,
  penilaian_awal_keperawatan_kebidanan.ket_provokes,
  penilaian_awal_keperawatan_kebidanan.quality,
  penilaian_awal_keperawatan_kebidanan.ket_quality,
  penilaian_awal_keperawatan_kebidanan.lokasi,
  penilaian_awal_keperawatan_kebidanan.menyebar,
  penilaian_awal_keperawatan_kebidanan.skala_nyeri,
  penilaian_awal_keperawatan_kebidanan.durasi,
  penilaian_awal_keperawatan_kebidanan.nyeri_hilang,
  penilaian_awal_keperawatan_kebidanan.ket_nyeri,
  penilaian_awal_keperawatan_kebidanan.pada_dokter,
  penilaian_awal_keperawatan_kebidanan.ket_dokter,
  penilaian_awal_keperawatan_kebidanan.masalah,
  penilaian_awal_keperawatan_kebidanan.tindakan,
  penilaian_awal_keperawatan_kebidanan.nip,
  petugas.nama,
  ( 
    select 
      CONCAT('[',
      GROUP_CONCAT(
        JSON_OBJECT(
          'tanggal_tahun', rpp.tgl_thn,
          'tempat_persalinan', rpp.tempat_persalinan,
          'usia_hamil', rpp.usia_hamil,
          'jenis_persalinan', rpp.jenis_persalinan,
          'penolong', rpp.penolong,
          'penyulit', rpp.penyulit,
          'jk', rpp.jk,
          'bbpb', rpp.bbpb,
          'keadaan',rpp.keadaan
        )
      ),']') 
    from riwayat_persalinan_pasien rpp
    where rpp.no_rkm_medis=reg_periksa.no_rkm_medis 
    order by rpp.tgl_thn 
  ) as 'riwayat_persalinan:sqlx::types::Json<Vec<RiwayatPersalinan>>'
from penilaian_awal_keperawatan_kebidanan 
inner join petugas on penilaian_awal_keperawatan_kebidanan.nip=petugas.nip 
inner join reg_periksa on reg_periksa.no_rawat = penilaian_awal_keperawatan_kebidanan.no_rawat
where penilaian_awal_keperawatan_kebidanan.no_rawat=?
