use sqlx::MySqlPool;

use super::RiwayatPersalinan;

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct AssesmenKebidananRanap {
    pub tanggal: chrono::NaiveDateTime,
    pub informasi: String,
    pub tiba_diruang_rawat: String,
    pub cara_masuk: String,
    pub keluhan: String,
    pub rpk: String,
    pub psk: String,
    pub rp: String,
    pub alergi: String,
    pub komplikasi_sebelumnya: String,
    pub keterangan_komplikasi_sebelumnya: String,
    pub riwayat_mens_umur: String,
    pub riwayat_mens_lamanya: String,
    pub riwayat_mens_banyaknya: String,
    pub riwayat_mens_siklus: String,
    pub riwayat_mens_ket_siklus: String,
    pub riwayat_mens_dirasakan: String,
    pub riwayat_perkawinan_status: String,
    pub riwayat_perkawinan_ket_status: String,
    pub riwayat_perkawinan_usia1: String,
    pub riwayat_perkawinan_ket_usia1: String,
    pub riwayat_perkawinan_usia2: String,
    pub riwayat_perkawinan_ket_usia2: String,
    pub riwayat_perkawinan_usia3: String,
    pub riwayat_perkawinan_ket_usia3: String,
    pub riwayat_persalinan_g: String,
    pub riwayat_persalinan_p: String,
    pub riwayat_persalinan_a: String,
    pub riwayat_persalinan_hidup: String,
    pub riwayat_hamil_hpht: Option<chrono::NaiveDate>,
    pub riwayat_hamil_usiahamil: String,
    pub riwayat_hamil_tp: Option<chrono::NaiveDate>,
    pub riwayat_hamil_imunisasi: String,
    pub riwayat_hamil_anc: String,
    pub riwayat_hamil_ancke: String,
    pub riwayat_hamil_ket_ancke: String,
    pub riwayat_hamil_keluhan_hamil_muda: String,
    pub riwayat_hamil_keluhan_hamil_tua: String,
    pub riwayat_kb: String,
    pub riwayat_kb_lamanya: String,
    pub riwayat_kb_komplikasi: String,
    pub riwayat_kb_ket_komplikasi: String,
    pub riwayat_kb_kapaberhenti: String,
    pub riwayat_kb_alasanberhenti: String,
    pub riwayat_genekologi: String,
    pub riwayat_kebiasaan_obat: String,
    pub riwayat_kebiasaan_ket_obat: String,
    pub riwayat_kebiasaan_merokok: String,
    pub riwayat_kebiasaan_ket_merokok: String,
    pub riwayat_kebiasaan_alkohol: String,
    pub riwayat_kebiasaan_ket_alkohol: String,
    pub riwayat_kebiasaan_narkoba: String,
    pub pemeriksaan_kebidanan_mental: String,
    pub pemeriksaan_kebidanan_keadaan_umum: String,
    pub pemeriksaan_kebidanan_gcs: String,
    pub pemeriksaan_kebidanan_td: String,
    pub pemeriksaan_kebidanan_nadi: String,
    pub pemeriksaan_kebidanan_rr: String,
    pub pemeriksaan_kebidanan_suhu: String,
    pub pemeriksaan_kebidanan_spo2: String,
    pub pemeriksaan_kebidanan_bb: String,
    pub pemeriksaan_kebidanan_tb: String,
    pub pemeriksaan_kebidanan_lila: String,
    pub pemeriksaan_kebidanan_tfu: String,
    pub pemeriksaan_kebidanan_tbj: String,
    pub pemeriksaan_kebidanan_letak: String,
    pub pemeriksaan_kebidanan_presentasi: String,
    pub pemeriksaan_kebidanan_penurunan: String,
    pub pemeriksaan_kebidanan_his: String,
    pub pemeriksaan_kebidanan_kekuatan: String,
    pub pemeriksaan_kebidanan_lamanya: String,
    pub pemeriksaan_kebidanan_djj: String,
    pub pemeriksaan_kebidanan_ket_djj: String,
    pub pemeriksaan_kebidanan_portio: String,
    pub pemeriksaan_kebidanan_pembukaan: String,
    pub pemeriksaan_kebidanan_ketuban: String,
    pub pemeriksaan_kebidanan_hodge: String,
    pub pemeriksaan_kebidanan_panggul: String,
    pub pemeriksaan_kebidanan_inspekulo: String,
    pub pemeriksaan_kebidanan_ket_inspekulo: String,
    pub pemeriksaan_kebidanan_lakmus: String,
    pub pemeriksaan_kebidanan_ket_lakmus: String,
    pub pemeriksaan_kebidanan_ctg: String,
    pub pemeriksaan_kebidanan_ket_ctg: String,
    pub pemeriksaan_umum_kepala: String,
    pub pemeriksaan_umum_muka: String,
    pub pemeriksaan_umum_mata: String,
    pub pemeriksaan_umum_hidung: String,
    pub pemeriksaan_umum_telinga: String,
    pub pemeriksaan_umum_mulut: String,
    pub pemeriksaan_umum_leher: String,
    pub pemeriksaan_umum_dada: String,
    pub pemeriksaan_umum_perut: String,
    pub pemeriksaan_umum_genitalia: String,
    pub pemeriksaan_umum_ekstrimitas: String,
    pub pengkajian_fungsi_kemampuan_aktifitas: String,
    pub pengkajian_fungsi_berjalan: String,
    pub pengkajian_fungsi_ket_berjalan: String,
    pub pengkajian_fungsi_aktivitas: String,
    pub pengkajian_fungsi_ambulasi: String,
    pub pengkajian_fungsi_ekstrimitas_atas: String,
    pub pengkajian_fungsi_ket_ekstrimitas_atas: String,
    pub pengkajian_fungsi_ekstrimitas_bawah: String,
    pub pengkajian_fungsi_ket_ekstrimitas_bawah: String,
    pub pengkajian_fungsi_kemampuan_menggenggam: String,
    pub pengkajian_fungsi_ket_kemampuan_menggenggam: String,
    pub pengkajian_fungsi_koordinasi: String,
    pub pengkajian_fungsi_ket_koordinasi: String,
    pub pengkajian_fungsi_gangguan_fungsi: String,
    pub riwayat_psiko_kondisipsiko: String,
    pub riwayat_psiko_adakah_prilaku: String,
    pub riwayat_psiko_ket_adakah_prilaku: String,
    pub riwayat_psiko_gangguan_jiwa: String,
    pub riwayat_psiko_hubungan_pasien: String,
    pub riwayat_psiko_tinggal_dengan: String,
    pub riwayat_psiko_ket_tinggal_dengan: String,
    pub riwayat_psiko_budaya: String,
    pub riwayat_psiko_ket_budaya: String,
    pub riwayat_psiko_pend_pj: String,
    pub riwayat_psiko_edukasi_pada: String,
    pub riwayat_psiko_ket_edukasi_pada: String,
    pub penilaian_nyeri: String,
    pub penilaian_nyeri_penyebab: String,
    pub penilaian_nyeri_ket_penyebab: String,
    pub penilaian_nyeri_kualitas: String,
    pub penilaian_nyeri_ket_kualitas: String,
    pub penilaian_nyeri_lokasi: String,
    pub penilaian_nyeri_menyebar: String,
    pub penilaian_nyeri_skala: String,
    pub penilaian_nyeri_waktu: String,
    pub penilaian_nyeri_hilang: String,
    pub penilaian_nyeri_ket_hilang: String,
    pub penilaian_nyeri_diberitahukan_dokter: String,
    pub penilaian_nyeri_jam_diberitahukan_dokter: String,
    pub penilaian_jatuh_skala1: String,
    pub penilaian_jatuh_nilai1: i8,
    pub penilaian_jatuh_skala2: String,
    pub penilaian_jatuh_nilai2: i8,
    pub penilaian_jatuh_skala3: String,
    pub penilaian_jatuh_nilai3: i8,
    pub penilaian_jatuh_skala4: String,
    pub penilaian_jatuh_nilai4: i8,
    pub penilaian_jatuh_skala5: String,
    pub penilaian_jatuh_nilai5: i8,
    pub penilaian_jatuh_skala6: String,
    pub penilaian_jatuh_nilai6: i8,
    pub penilaian_jatuh_totalnilai: f64,
    pub skrining_gizi1: String,
    pub nilai_gizi1: i32,
    pub skrining_gizi2: String,
    pub nilai_gizi2: i32,
    pub nilai_total_gizi: f64,
    pub skrining_gizi_diagnosa_khusus: String,
    pub skrining_gizi_ket_diagnosa_khusus: String,
    pub skrining_gizi_diketahui_dietisen: String,
    pub skrining_gizi_jam_diketahui_dietisen: String,
    pub masalah: String,
    pub rencana: String,
    pub nip1: String,
    pub nip2: String,
    pub kd_dokter: String,
    pub pengkaji1: Option<String>,
    pub pengkaji2: Option<String>,
    pub nm_dokter: Option<String>,
    pub riwayat_persalinan: Option<sqlx::types::Json<Vec<RiwayatPersalinan>>>,
}

pub async fn get_assesmen_kebidanan_ranap(
    db: &MySqlPool,
    no_rawat: &str,
) -> sqlx::Result<Option<AssesmenKebidananRanap>> {
    sqlx::query_file_as!(
        AssesmenKebidananRanap,
        "./src/dto/assesmen_kebidanan/get-assesmen-bidan-ranap.sql",
        no_rawat
    )
    .fetch_optional(db)
    .await
}
