SELECT
       resume_pasien_ranap.kd_dokter as kode_dokter,
       dokter.nm_dokter as nama_dokter,
       resume_pasien_ranap.diagnosa_awal,
       resume_pasien_ranap.alasan,
       resume_pasien_ranap.keluhan_utama,
       resume_pasien_ranap.pemeriksaan_fisik,
       resume_pasien_ranap.jalannya_penyakit,
       resume_pasien_ranap.pemeriksaan_penunjang,
       resume_pasien_ranap.hasil_laborat,
       resume_pasien_ranap.tindakan_dan_operasi,
       resume_pasien_ranap.obat_di_rs as obat_rs,
       resume_pasien_ranap.diagnosa_utama,
       resume_pasien_ranap.kd_diagnosa_utama,
       resume_pasien_ranap.diagnosa_sekunder,
       resume_pasien_ranap.kd_diagnosa_sekunder,
       resume_pasien_ranap.diagnosa_sekunder2,
       resume_pasien_ranap.kd_diagnosa_sekunder2,
       resume_pasien_ranap.diagnosa_sekunder3,
       resume_pasien_ranap.kd_diagnosa_sekunder3,
       resume_pasien_ranap.diagnosa_sekunder4,
       resume_pasien_ranap.kd_diagnosa_sekunder4,
       resume_pasien_ranap.prosedur_utama,
       resume_pasien_ranap.kd_prosedur_utama,
       resume_pasien_ranap.prosedur_sekunder,
       resume_pasien_ranap.kd_prosedur_sekunder,
       resume_pasien_ranap.prosedur_sekunder2,
       resume_pasien_ranap.kd_prosedur_sekunder2,
       resume_pasien_ranap.prosedur_sekunder3,
       resume_pasien_ranap.kd_prosedur_sekunder3,
       resume_pasien_ranap.alergi,
       resume_pasien_ranap.diet,
       resume_pasien_ranap.lab_belum,
       resume_pasien_ranap.edukasi,
       resume_pasien_ranap.cara_keluar,
       resume_pasien_ranap.ket_keluar,
       resume_pasien_ranap.keadaan,
       resume_pasien_ranap.ket_keadaan,
       resume_pasien_ranap.dilanjutkan,
       resume_pasien_ranap.ket_dilanjutkan,
       resume_pasien_ranap.kontrol,
       resume_pasien_ranap.obat_pulang
FROM resume_pasien_ranap
INNER JOIN dokter ON resume_pasien_ranap.kd_dokter=dokter.kd_dokter
WHERE resume_pasien_ranap.no_rawat=?
